"""Shared setup tooling for ATLAS."""

from .controller import (
    AdminProfile,
    BootstrapError,
    ConfigManager,
    DatabaseState,
    HardwareProfile,
    JobSchedulingState,
    KvStoreState,
    MessageBusState,
    OptionalState,
    PrivilegedCredentialState,
    ProviderState,
    RAGState,
    RetryPolicyState,
    SetupTypeState,
    SetupUserEntry,
    SetupUsersState,
    SetupWizardController,
    SpeechState,
    UserState,
    VectorStoreState,
)
from .rag_capabilities import (
    EmbeddingTier,
    GPUInfo,
    PgVectorInfo,
    EmbeddingModelRecommendation,
    RAGCapabilities,
    RAGCapabilitiesDetector,
    detect_rag_capabilities,
    EMBEDDING_MODEL_CATALOG,
)

__all__ = [
    "AdminProfile",
    "BootstrapError",
    "ConfigManager",
    "DatabaseState",
    "HardwareProfile",
    "JobSchedulingState",
    "KvStoreState",
    "MessageBusState",
    "OptionalState",
    "PrivilegedCredentialState",
    "ProviderState",
    "RAGState",
    "RetryPolicyState",
    "SetupTypeState",
    "SetupUserEntry",
    "SetupUsersState",
    "SetupWizardController",
    "SpeechState",
    "UserState",
    "VectorStoreState",
    # RAG capabilities
    "EmbeddingTier",
    "GPUInfo",
    "PgVectorInfo",
    "EmbeddingModelRecommendation",
    "RAGCapabilities",
    "RAGCapabilitiesDetector",
    "detect_rag_capabilities",
    "EMBEDDING_MODEL_CATALOG",
]
